---
deployment:
  tasks:
    # 1️⃣ Set deployment path
    - export DEPLOYPATH=/home/hoautosp/public_html/

    # 2️⃣ Sync all files from repo to public_html
    - /bin/rsync -av --delete ./ $DEPLOYPATH

    # 3️⃣ Set correct permissions
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;

    # 4️⃣ Cache-bust your assets (force browsers to reload)
    - /usr/bin/sed -i "s?v=[0-9]\+?v=$(date +%s)?g" $DEPLOYPATH/index.html

    # 5️⃣ Optional: log deployment
    - echo "Deployment completed on $(date)" >> $DEPLOYPATH/deploy.log
